### PR TITLE
[MAS4.2.1] [Screen reader -Debug] In forward navigation NVDA is not reading the under JSON tab section controls information

### PR DESCRIPTION
**Pull request by Bill7zz**
Solves #XXX

### Description
This pull request enables the NVDA to read the content of the JSON web viewer. 

### Changes made
- Remove tab index from panel content to allow the Screen Reader to read the content of the JSON tree view.

The panel content had an attribute `tabindex` which causes conflicts with the screen reader navigation using the `tab` control.
image

### Test
We navigate through the component using the `tab` control and the NVDA read the information of the elements as we expected. 
image

### CODE REVIEW

**Comment by GiulianoDolceTalianoSantoro** [comment]
Shouldn't the image have a border? Besides that it looks good!

**Comment by Maihav** [comment]
Just a few questions regarding the doc:
- What is the `SR`? Did you refer to the Screen Reader? 
- Can you add a blank line between the last sentence and the image? Or maybe a border image to define it better.

To be consistents, add a final dot to all the sentences.

**Comment by Bill7zz** [comment]
Applied

**Comment by Bill7zz** [comment]
Merge MS PR 1923
image

**Pull request closed without merging**
